name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1

      - name: buf lint
        run: buf lint

      - name: buf breaking
        if: github.event_name == 'pull_request'
        run: buf breaking --against 'https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }}'

  push:
    needs: lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}

      - name: buf push
        run: buf push
